export async function runTaskChecks({db,a,b,outsider,equal,denied,identity,scalar}) {
 await identity(a);
 const event=await scalar("select (public.create_event(gen_random_uuid(),'Tasks',2026,'2026-09-01','2026-09-20','USD')).id");
 const other=await scalar("select (public.create_event(gen_random_uuid(),'Other tasks',2026,'2026-09-01','2026-09-20','USD')).id");
 const json=o=>"'"+JSON.stringify(o).replaceAll("'","''")+"'::jsonb";
 const save=(fields,id=null,v=null,scope=event,request='gen_random_uuid()')=>`select public.save_task('${scope}',${request},${id?`'${id}'`:'null'},${v??'null'},${json(fields)})`;
 const fields={title:'Call landlord'};
 const req="'89111111-1111-4111-8111-111111111111'";
 const id=await scalar(save(fields,null,null,event,req));
 const read=k=>`select public.read_task('${event}','${id}')->'${k}'`;
 const version=()=>scalar(`select version::int from public.tasks where id='${id}'`);
 await equal(save(fields,null,null,event,req),id);
 await equal(`select count(*)::int from public.audit_entries where entity_id='${id}'`,1);
 for(const k of ['priority','assignee_id','due_date_utc','description','notes']) await equal(read(k),null);
 await equal(read('title'),'Call landlord');
 await denied(save({...fields,title:'Changed retry'},null,null,event,req),'40001');
 await denied(save(fields,null,null,other,req),'42501');
 for(const bad of [{...fields,status:'COMPLETED'},{...fields,created_by:b},{...fields,version:5},{...fields,completed_at_utc:'2026-09-30Z'}]) await denied(save(bad),'22023');
 for(const bad of [{title:''},{title:' '.repeat(3)},{title:'x'.repeat(501)},{...fields,notes:'x'.repeat(10001)},{...fields,priority:'URGENT'},{...fields,due_date_utc:'infinity'}]) await denied(save(bad),'23514');
 await denied(save({...fields,title:123}),'22023');
 const person=await scalar(`select public.save_person('${event}',gen_random_uuid(),null,null,'{"first_name":"Responsible","status":"ACTIVE"}'::jsonb)`);
 const foreign=await scalar(`select public.save_person('${other}',gen_random_uuid(),null,null,'{"first_name":"Foreign","status":"ACTIVE"}'::jsonb)`);
 await denied(save({...fields,assignee_id:foreign}),'23503');
 await db.exec('reset role');
 await denied(`update public.tasks set assignee_id='${foreign}' where id='${id}'`,'23503');
 await identity(a);
 await db.exec(save({...fields,assignee_id:person,priority:'HIGH',due_date_utc:'2026-09-01T10:00:00+03:00'},id,1));
 await equal(`select due_date_utc='2026-09-01T07:00:00Z'::timestamptz from public.tasks where id='${id}'`,true);
 await denied(save(fields,id,1),'40001');
 await equal(read('version'),2);
 // Deleted assignees remain linked until the manager changes them explicitly.
 await db.exec(`select public.set_person_deleted('${event}','${person}',1,true)`);
 await denied(save({...fields,assignee_id:person}),'23503');
 await db.exec(save({...fields,assignee_id:person},id,2));
 await equal(read('assignee_id'),person);
 await equal(`select x->'is_deleted' from public.task_assignees('${event}') x where x->>'id'='${person}'`,true);
 const move=(status,v,scope=event)=>`select public.transition_task('${scope}','${id}',${v},'${status}')`;
 // This branch's initial-state policy is checked separately after owner clarification.
 if(await scalar(read('status'))===null) await db.exec(move('NEW',await version()));
 await denied(move('COMPLETED',await version()),'22023');
 for(const status of ['IN_PROGRESS','WAITING','IN_PROGRESS','COMPLETED']) await db.exec(move(status,await version()));
 await equal(read('status'),'COMPLETED');
 await equal(`select completed_at_utc is not null and cancelled_at_utc is null from public.tasks where id='${id}'`,true);
 const completed=await scalar(read('completed_at_utc'));
 await db.exec(save({...fields,notes:'Review complete'},id,await version()));
 await equal(read('completed_at_utc'),completed);
 await db.exec(move('WAITING',await version()));
 await equal(read('completed_at_utc'),null);
 await db.exec(move('CANCELLED',await version()));
 await equal(`select cancelled_at_utc is not null from public.tasks where id='${id}'`,true);
 await denied(move('COMPLETED',await version()),'22023');
 await db.exec(move('NEW',await version()));
 await equal(read('cancelled_at_utc'),null);
 await denied(move('IN_PROGRESS',1),'40001');
 await denied(move('IN_PROGRESS',await version(),other),'42501');
 let v=await version();
 await db.exec(`select public.delete_task('${event}','${id}',${v})`);
 await equal(`select count(*)::int from public.list_tasks('${event}')`,0);
 await equal(`select count(*)::int from public.list_tasks('${event}','',true)`,1);
 await denied(move('IN_PROGRESS',await version()),'40001');
 await denied(save(fields,id,await version()),'40001');
 await denied(`select public.restore_task('${event}','${id}',${v})`,'40001');
 await db.exec(`select public.restore_task('${event}','${id}',${await version()})`);
 await equal(read('status'),'NEW');
 await equal(`select count(*)::int from public.list_tasks('${event}','landlord')`,1);
 await equal(`select count(*)::int from public.list_tasks('${other}')`,0);
 await equal(`select count(*)::int from public.list_tasks('${event}','%')`,0);
 await equal(`select public.read_task('${other}','${id}')`,null);
 await equal(`select count(*)::int from public.audit_entries where entity_id='${id}' and actor_user_id<>'${a}'`,0);
 await equal(`select count(*)::int from public.audit_entries where entity_id='${id}'`,await version());
 await equal(`select count(*)::int from public.audit_entries where entity_id='${id}' and new_value ? 'creation_payload'`,0);
 await denied(`update public.audit_entries set operation='ALTERED' where entity_id='${id}'`,'42501');
 await denied(`insert into public.tasks(event_id,title,created_by,updated_by) values('${event}','Bypass','${a}','${a}')`,'42501');
 await denied(`update public.tasks set title='Bypass' where id='${id}'`,'42501');
 await denied(`delete from public.tasks where id='${id}'`,'42501');
 // Another member gets server attribution, and old CAS cannot overwrite their change.
 await db.exec(`reset role; insert into public.event_members(event_id,user_id,role,created_by) values('${event}','${b}','administrator','${a}')`);
 await identity(b);v=await version();await db.exec(save({...fields,notes:'Second manager'},id,v));
 await equal(read('updated_by'),b);
 await identity(a);await denied(save(fields,id,v),'40001');
 // Auditing is in the same transaction; rejection cannot leave source/version changes.
 await db.exec(`reset role; create function public.reject_task_audit() returns trigger language plpgsql as $$ begin if new.entity_type='tasks' then raise exception 'test'; end if; return new; end; $$; create trigger reject_task_audit before insert on public.audit_entries for each row execute function public.reject_task_audit();`);
 await identity(a);v=await version();
 await denied(save({...fields,title:'Rollback'},id,v),'P0001');
 await equal(read('version'),v);await equal(read('title'),'Call landlord');
 await denied(move('IN_PROGRESS',v),'P0001');await equal(read('version'),v);
 await db.exec('reset role; drop trigger reject_task_audit on public.audit_entries; drop function public.reject_task_audit();');
 await equal(`select count(*)::int from pg_publication_tables where pubname='supabase_realtime' and tablename='tasks'`,1);
 await equal(`select relrowsecurity from pg_class where oid='public.tasks'::regclass`,true);
 await equal(`select count(*)::int from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname in ('public','tasks_private') and (p.proname like '%task%' or n.nspname='tasks_private') and has_function_privilege('anon',p.oid,'EXECUTE')`,0);
 await equal(`select count(*)::int from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='tasks_private' and has_function_privilege('authenticated',p.oid,'EXECUTE')`,0);
 await identity(outsider);await equal('select count(*)::int from public.tasks',0);
 await denied(`select public.list_tasks('${event}')`,'42501');await denied(save(fields),'42501');
 await denied(move('IN_PROGRESS',v),'42501');
 await identity('','anon');await denied('select * from public.tasks','42501');await denied(`select public.list_tasks('${event}')`,'42501');
 await identity(a);await db.exec(`select public.archive_event('${event}',1)`);
 await denied(save(fields),'40001');await denied(move('IN_PROGRESS',v),'40001');
 await denied(`select public.delete_task('${event}','${id}',${v})`,'40001');
 await db.exec(`reset role; delete from public.event_members where event_id='${event}' and user_id='${b}'`);
 await identity(b);await denied(`select public.list_tasks('${event}')`,'42501');await equal(`select count(*)::int from public.tasks where event_id='${event}'`,0);
 await identity(a);
}
