export async function runTripChecks({db,a,outsider,equal,denied,identity,scalar}) {
 await identity(a);
 const event=await scalar("select (public.create_event(gen_random_uuid(),'Trip checks',2026,'2026-09-01','2026-09-20','USD')).id");
 const other=await scalar("select (public.create_event(gen_random_uuid(),'Other trip checks',2026,'2026-09-01','2026-09-20','USD')).id");
 const json=o=>"'"+JSON.stringify(o).replaceAll("'","''")+"'::jsonb";
 const save=(table,fields,id=null,version=null,scope=event,request='gen_random_uuid()')=>`select public.save_${table}('${scope}',${request},${id?`'${id}'`:'null'},${version??'null'},${json(fields)})`;
 const driver=await scalar(save('driver',{full_name:'Trip driver',status:'AVAILABLE'}));
 const vehicle=await scalar(save('vehicle',{name:'Trip van',vehicle_type:'VAN',capacity:1,status:'AVAILABLE'}));
 const flightFields={airline:'Test carrier',flight_number:'T1',departure_airport:'AAA',arrival_airport:'BBB',direction:'INBOUND',scheduled_departure_utc:'2026-09-01T10:00:00Z',scheduled_arrival_utc:'2026-09-01T12:00:00Z',status:'SCHEDULED'};
 const flight=await scalar(save('flight',flightFields));
 const person=await scalar(save('person',{first_name:'Trip',last_name:'Passenger',status:'ACTIVE'}));
 const person2=await scalar(save('person',{first_name:'Second',last_name:'Passenger',status:'ACTIVE'}));
 const fields={direction:'INBOUND',origin:'Airport',destination:'Uman',scheduled_departure_utc:'2026-09-01T13:00:00Z',scheduled_arrival_utc:'2026-09-01T16:00:00Z',status:'PLANNED',is_locked:false,driver_id:driver,vehicle_id:vehicle,related_flight_id:flight};
 const request="'ab111111-1111-4111-8111-111111111111'";
 const trip=await scalar(save('trip',fields,null,null,event,request));
 await equal(save('trip',fields,null,null,event,request),trip);
 await denied(save('trip',{...fields,origin:'Changed retry'},null,null,event,request),'40001');
 const read=key=>`select public.read_trip('${event}','${trip}')->'${key}'`;
 await equal(read('active_passengers'),0);
 await equal(read('vehicle_capacity'),1);
 await equal(read('flight_needs_review'),false);
 await equal(read('driver_id'),driver);
 await equal(read('related_flight_id'),flight);
 for(const key of ['driver_id','vehicle_id','related_flight_id']) {
  const entity=key==='driver_id'?'driver':key==='vehicle_id'?'vehicle':'flight';
  const foreign=await scalar(save(entity,entity==='driver'?{full_name:'Foreign',status:'AVAILABLE'}:entity==='vehicle'?{name:'Foreign',vehicle_type:'VAN',capacity:1,status:'AVAILABLE'}:flightFields,null,null,other));
  await denied(save('trip',{...fields,[key]:foreign}),'23503');
  await db.exec('reset role');
  await denied(`update public.trips set ${key}='${foreign}' where id='${trip}'`,'23503');
  await identity(a);
 }
 await denied(save('trip',{...fields,scheduled_arrival_utc:fields.scheduled_departure_utc}),'23514');
 await denied(save('trip',{...fields,origin:''}),'23514');
 await denied(save('trip',{...fields,status:'INVALID'}),'23514');
 await denied(save('trip',{...fields,event_id:other}),'22023');
 const pf={trip_id:trip,person_id:person,passenger_status:'ASSIGNED',pickup_location:null};
 const p=await scalar(save('trip_passenger',pf));
 await equal(read('active_passengers'),1); // exact capacity valid
 await equal(`select count(*)::int from public.list_trip_passengers('${event}','${trip}')`,1);
 const p2=await scalar(save('trip_passenger',{...pf,person_id:person2}));
 await equal(read('active_passengers'),2); // overflow accepted without eviction
 await equal(`select count(*)::int from public.trip_passengers where trip_id='${trip}' and not is_deleted`,2);
 await db.exec(save('trip_passenger',{...pf,person_id:person2,passenger_status:'CANCELLED'},p2,1));
 await equal(read('active_passengers'),1);
 await db.exec(`select public.delete_trip_passenger('${event}','${p}',1)`);
 await equal(read('active_passengers'),0);
 await db.exec(`select public.restore_trip_passenger('${event}','${p}',2)`);
 await equal(read('active_passengers'),1);
 await equal(`select pickup_location from public.trip_passengers where id='${p}'`,null);
 await denied(save('trip_passenger',pf,p,1),'40001');
 await denied(save('trip_passenger',pf),'23505');
 const foreignPerson=await scalar(save('person',{first_name:'Other',last_name:'Person',status:'ACTIVE'},null,null,other));
 await denied(save('trip_passenger',{...pf,person_id:foreignPerson}),'23503');
 await denied(save('trip_passenger',pf,null,null,other),'23503');
 await db.exec('reset role');
 await denied(`update public.trip_passengers set person_id='${foreignPerson}' where id='${p}'`,'23503');
 await denied(`update public.trip_passengers set event_id='${other}' where id='${p}'`,'23503');
 await identity(a);
 await db.exec(save('trip',{...fields,actual_arrival_utc:'2026-09-01T16:30:00Z',is_locked:true},trip,1));
 await equal(read('status'),'PLANNED');
 await equal(read('is_locked'),true);
 await denied(save('trip',fields,trip,1),'40001');
 await db.exec(save('flight',{...flightFields,status:'DELAYED'},flight,1));
 await equal(read('flight_needs_review'),true);
 await equal(`select scheduled_departure_utc='2026-09-01T13:00:00Z'::timestamptz from public.trips where id='${trip}'`,true);
 await db.exec(save('trip',{...fields,notes:'Manager edit'},trip,2));
 await equal(read('flight_needs_review'),true); // ordinary edits never dismiss advisory
 await equal(`select count(*)::int from public.list_trips('${event}','Airport',false)`,1);
 await equal(`select count(*)::int from public.list_trips('${other}','Airport',false)`,0);
 await db.exec(`select public.delete_trip('${event}','${trip}',3)`);
 await equal(`select count(*)::int from public.list_trips('${event}','',false)`,0);
 await equal(`select count(*)::int from public.list_trips('${event}','',true)`,1);
 await denied(save('trip_passenger',{...pf,person_id:person2}),'23503');
 await db.exec(`select public.restore_trip('${event}','${trip}',4)`);
 await equal(read('version'),5);
 await denied(`select public.delete_trip('${event}','${trip}',4)`,'40001');
 await equal(`select count(*)::int from public.audit_entries where entity_id='${trip}'`,5);
 await equal(`select count(*)::int from public.audit_entries where entity_id='${trip}' and actor_user_id<>'${a}'`,0);
 await equal(`select count(*)::int from public.audit_entries where entity_id='${trip}' and (new_value ? 'creation_payload' or new_value ? 'creation_request_id')`,0);
 // Audit failure must roll back both source and version.
 await db.exec(`reset role; create function public.reject_trip_audit() returns trigger language plpgsql as $$ begin if new.entity_type in ('trips','trip_passengers') then raise exception 'audit test'; end if; return new; end; $$; create trigger reject_trip_audit before insert on public.audit_entries for each row execute function public.reject_trip_audit();`);
 await identity(a);
 await denied(save('trip',fields,trip,5),'P0001');
 await equal(read('version'),5);
 await denied(save('trip_passenger',{...pf,pickup_location:'Changed'},p,3),'P0001');
 await equal(`select version::int from public.trip_passengers where id='${p}'`,3);
 await equal(`select pickup_location from public.trip_passengers where id='${p}'`,null);
 await db.exec('reset role; drop trigger reject_trip_audit on public.audit_entries; drop function public.reject_trip_audit();');
 await equal(`select count(*)::int from pg_publication_tables where pubname='supabase_realtime' and tablename in ('trips','trip_passengers')`,2);
 await equal(`select count(*)::int from pg_class where relname in ('trips','trip_passengers') and relrowsecurity`,2);
 await equal(`select count(*)::int from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname like '%trip%' and has_function_privilege('anon',p.oid,'EXECUTE')`,0);
 await identity(outsider);
 await equal('select count(*)::int from public.trips',0);
 await equal('select count(*)::int from public.trip_passengers',0);
 await denied(`select public.list_trips('${event}')`,'42501');
 await denied(save('trip',fields),'42501');
 await identity(a);
 await denied(`update public.trips set origin='Bypass' where id='${trip}'`,'42501');
 await denied(`delete from public.trip_passengers where id='${p}'`,'42501');
 await db.exec(`select public.archive_event('${event}',1)`);
 await denied(save('trip',fields,trip,5),'40001');
 await identity('','anon');
 await denied(`select public.list_trips('${event}')`,'42501');
 await denied('select * from public.trips','42501');
 await identity(a);
}
